## ACADEMIC INTEGRITY

NAU expects every student to firmly adhere to a strong ethical code of academic integrity in all their scholarly pursuits. The primary attributes of academic integrity are honesty, trustworthiness, fairness, and responsibility. As a student, you are expected to submit original work while giving proper credit to other people’s ideas or contributions. Acting with academic integrity means completing your assignments independently while truthfully acknowledging all sources of information, or collaboration with others when appropriate. When you submit your work, you are implicitly declaring that the work is your own. Academic integrity is expected not only during formal coursework, but in all your relationships or interactions that are connected to the educational enterprise. All forms of academic deceit such as plagiarism, cheating, collusion, falsification or fabrication of results or records, permitting your work to be submitted by another, or inappropriately recycling your own work from one class to another, constitute academic misconduct that may result in serious disciplinary consequences. All students and faculty members are responsible for reporting suspected instances of academic misconduct. All students are encouraged to complete the online course entitled **Academic Integrity @NAU for Students** found in their Canvas Dashboard and review the full [NAU Academic Integrity Policy](https://www9.nau.edu/policies/Client/Details/1443?whoIsLooking=Students&pertainsTo=All).

## ARTIFICIAL INTELLIGENCE

Artificial intelligence (AI) technologies bring both opportunities and challenges. Ensuring honesty in academic work creates a culture of integrity and expectations of ethical behavior. The use of these technologies can depend on the instructional setting, varying by faculty member, program, course, and assignment. Please refer to course policies, any additional course-specific guidelines in the syllabus, or communicate with the instructor to understand expectations. NAU recognizes the role that these technologies will play in the current and future careers of our graduates and expects students to practice responsible and ethical use of AI technologies to assist with learning within the confines of course policies.

## COPYRIGHT INFRINGEMENT

All lectures and course materials, including but not limited to exams, quizzes, study outlines, and similar materials are protected by copyright. These materials may not be shared, uploaded, distributed, reproduced, or publicly displayed without the express written permission of NAU. Sharing materials on websites such as Course Hero, Chegg, or related websites is considered copyright infringement subject to United States Copyright Law and a violation of NAU Student Code of Conduct. For more information on ABOR policies relating to course materials, please refer to [ABOR Policy 6-908 A(2)(5)](https://public.powerdms.com/ABOR/documents/1499354).

## COURSE TIME COMMITMENT

Pursuant to Arizona Board of Regents guidance ([ABOR Policy 2-224](https://public.powerdms.com/ABOR/documents/1491660), *Academic Credit*), each unit of credit requires a minimum of 45 hours of work by students, including but not limited to, class time, preparation, homework, and studying. For example, for a 3-credit course a student should expect to work at least 8.5 hours each week in a 16-week session and a minimum of 33 hours per week for a 3-credit course in a 4-week session.

## DISRUPTIVE BEHAVIOR

Membership in NAU’s academic community entails a special obligation to maintain class environments that are conductive to learning, whether instruction is taking place in the classroom, a laboratory or clinical setting, during course-related fieldwork, or online. Students have the obligation to engage in the educational process in a manner that does not interfere with normal class activities or violate the rights of others. For more information, see the [Student Code of Conduct policy](https://legacy.nau.edu/university-policy-library/student-code-of-conduct/).

## NONDISCRIMINATION AND ANTI-HARASSMENT

NAU prohibits discrimination and harassment based on sex, gender, gender identity, race, color, age, national origin, religion, sexual orientation, disability, veteran status and genetic information. Certain consensual amorous or sexual relationships between faculty and students are also prohibited as set forth in the [Consensual Romantic and Sexual Relationships Policy](https://in.nau.edu/university-policy-library/wp-content/uploads/sites/395/Consensual-Romantic-or-Sexual-Relationships.pdf). The Office of Civil Rights Compliance (OCRC) responds to complaints regarding discrimination and harassment that fall under NAU’s [Nondiscrimination and Anti- Harassment Policy](https://in.nau.edu/university-policy-library/wp-content/uploads/sites/395/accessible_07-30-25-Nondiscrimination-and-Anti-Harassment-Policy.pdf). To report a concern related to possible unlawful discrimination or harassment, to request a time to confer, or file a complaint, please use the "Report Discrimination – NAU Login" button located at https://in.nau.edu/office-civil-rights-compliance/. OCRC also receives, evaluates, and engages in the interactive process relating to requests for religious accommodations. One may request a religious accommodation by submitting the "Request a Religious Accommodation/Adjustment Form" located at https://in.nau.edu/office-civil-rights-compliance/religious-accommodation-adjustment/. OCRC additionally provides access to lactation spaces, and please use to the [Lactation Space Request Form for Employees and Students](https://in.nau.edu/office-civil-rights-compliance/lactation-rooms/) to request use of a location. For additional information about nondiscrimination or anti-harassment, contact OCRC at [OCRC@nau.edu,](mailto:OCRC@nau.edu) or visit the OCRC website at https://in.nau.edu/office-civil-rights-compliance/. OCRC is located in Old Main on the first floor.

## TITLE IX

Title IX of the Education Amendments of 1972, as amended, protects individuals from discrimination based on sex in any educational program or activity operated by recipients of federal financial assistance. In accordance with Title IX, Northern Arizona University prohibits discrimination based on sex in all its programs or activities. Sex discrimination includes sexual harassment, sexual assault, relationship violence, stalking, and other forms of sexual harassment. NAU does not discriminate on the basis of sex in the education programs or activities that it operates, including in admission and employment. NAU is committed to providing an environment free from discrimination based on sex and offers a number of supportive measures that assist students, faculty and staff employees, affiliates, and guests.

One may direct inquiries concerning the application of Title IX to either or both the university Title IX Coordinator or the U.S. Department of Education, Assistant Secretary, Office of Civil Rights. You may contact NAU's Title IX Coordinator at <titleix@nau.edu> or by phone at 928-523-5434. In furtherance of its Title IX obligations, NAU promptly will investigate or equitably resolve all reports of sex-based discrimination, including harassment or forms sexual misconduct and will eliminate any hostile environment as defined by law. To submit a report, please use the [File a Report Form](https://cm.maxient.com/reportingform.php?NorthernAZUniv&layout_id=52). The Office of Civil Rights Compliance and Title IX (OCRC-TIX) addresses matters that fall under the university's [Sexual Misconduct Policy](https://nau.edu/wp-content/uploads/sites/26/Sexual-Misconduct.pdf), and the Office of Title IX Compliance and Services (TIXCS) facilitates reasonable modifications for pregnant or parenting individuals. Additional important information and related resources, including how to request help or confidential support following conduct covered by the Sexual Misconduct Policy, is available on the [TIXCS web site](https://in.nau.edu/title-ix/), and you also may contact the office at <titleix@nau.edu>. The TIXCS is located in Old Main on the first floor.

## RELIGIOUS OBSERVANCES FOR STUDENTS

Students seeking to miss class or request other course-related adjustments to participate in a religious observance must submit the [Religious Accommodation and Adjustment Request Form](https://in.nau.edu/eao/religious-accommodation-adjustment/). The submission of the form initiates an interactive process that may include the student and relevant parties, as the Office of Civil Rights Compliance (OCRC) deems necessary. If OCRC approves the request, OCRC will provide the student and faculty member with a memo detailing the approved adjustments. For additional information, please visit https://in.nau.edu/office-civil-rights-compliance/religious-accommodation-adjustment/.

Students must submit the request by the second week of a regular term course or as soon as possible upon learning of the need for the requested academic adjustment. In general, the university will not retroactively apply a religious adjustment.

## ACCESSIBILITY

Professional disability specialists are available at Disability Resources to facilitate a range of academic support services and accommodations for individuals with disabilities. If you have a documented disability, you can request assistance by contacting Disability Resources at 928-523-8773 (voice), 928-523-8747 (fax), or <dr@nau.edu> (e-mail). Once eligibility has been determined, students register with Disability Resources every semester to activate their approved accommodations. Although a student may request an accommodation at any time, it is best to initiate the application process at least four weeks before a student wishes to receive an accommodation. Students may begin the accommodation process by submitting a [self-identification form](https://clockwork.nau.edu/user/intake/default.aspx) online or by contacting Disability Resources. The Director of Disability Resources, Jamie Axelrod, serves as NAU’s Americans with Disabilities Act Coordinator and Section 504 Compliance Officer. He can be reached at <jamie.axelrod@nau.edu>

## RESPONSIBLE CONDUCT OF RESEARCH

Students who engage in research at NAU must receive appropriate Responsible Conduct of Research (RCR) training. This instruction is designed to help ensure proper awareness and application of well-established professional norms and ethical principles related to the performance of all scientific research activities. For more information and details, students are encouraged to navigate to the complete policy on [Responsible Conduct of Research Training](https://legacy.nau.edu/university-policy-library/rcr-training/).

## MISCONDUCT IN RESEARCH

As noted, NAU expects every student to firmly adhere to a strong code of academic integrity in all their scholarly pursuits. This includes avoiding fabrication, falsification, or plagiarism when conducting research or reporting research results. Engaging in research misconduct may result in serious disciplinary consequences. Students must also report any suspected or actual instances of research misconduct of which they become aware. Allegations of research misconduct should be reported to your instructor or the University’s Research Integrity Officer, Scott Pryor, who can be reached at [scott.pryor@nau.edu](mailto:scott.pryor@nau.edu) or 928-523-5927. Students are encouraged to view the complete policy on [Misconduct in Research](https://legacy.nau.edu/university-policy-library/misconduct-in-research/).

## SENSITIVE COURSE MATERIALS

University education aims to expand student understanding and awareness. Thus, it necessarily involves engagement with a wide range of information, ideas, and creative representations. In their college studies, students can expect to encounter and to critically appraise materials that may differ from and perhaps challenge familiar understandings, ideas, and beliefs. Students are encouraged to discuss these matters with faculty.

Last revised August 4, 2026
